### ISSUE TITLE
Problem with install

### ISSUE THREAD

**Issue by jpdna** [biocommons/hgvs-eval#18]
Following the current README, I got various errors when running `make devready`, the first being
a problem with install pysam.

I ended up manually running:
pip install -r
on etc/develop.reqs and etc/install.reqs
and then `make devready`

after that I could run
`python app.py &`
successfully.

Has anyone else had success with the README in a fresh virtualenv

**Comment by reece** [comment]
It works for me as advertised on Ubuntu 16.04, w/Python 2.7.12.

```
snafu$ (set -x; make cleanest; make devready) 2>&1 | tee log.txt
snafu$ tail log
Searching for wcwidth==0.1.7
Best match: wcwidth 0.1.7
Adding wcwidth 0.1.7 to easy-install.pth file

Using /home/reece/projects/biocommons/hgvs-eval/venv/lib/python2.7/site-packages
Finished processing dependencies for hgvseval==0.0.1.dev18+naf64e28469ad
make[1]: Leaving directory '/home/reece/projects/biocommons/hgvs-eval'
#############################################################################
###  Do not forget to `source venv/bin/activate` to use this environment  ###
#############################################################################

```

Details at [log.txt](https://github.com/biocommons/hgvs-eval/files/579360/log.txt)

That's not to say that the devready scheme isn't broken somewhere, but rather that it _does_ work in at least one context.

**Comment by jpdna** [comment]
So, I was able to follow Reece's instructions above, and get server running and the example curl to work once I
1) removed anaconda from my PATH
2) realized that the code starts its own venv that I need to activate as per its output, not just use one I create ahead of time

I'm running ubutnu 16.04

HOWEVER, running:

```
hgvs-eval --html report.html --json report.json http://0.0.0.0:8000/
```

produces all kinds of error messages that I excerpt below

```
 hgvs-eval --html report.html --json report.json http://0.0.0.0:8000/
Starting HGVS-eval tests for endpoint: http://0.0.0.0:8000/

HGVS Endpoint: http://0.0.0.0:8000/
rootdir: /home/paschallj/hgvs_eval/v5/hgvs-eval, inifile: pytest.ini
plugins: json-0.4.0, html-1.11.0, cov-2.4.0
collected 18 items 

tests/test_hgvs.py Testing HGVS service info endpoint on: http://0.0.0.0:8000/info
127.0.0.1 - - [09/Nov/2016 08:32:43] "GET /info HTTP/1.1" 200 -
{u'packageVersion': u'0.5.0a6', u'nomenclatureVersion': u'yeah, right', u'evalVersion': u'0.0.1.dev23+ng015a294'}
.Testing HGVS operation on: http://0.0.0.0:8000/project_g_to_t
project_g_to_t(None, None)
127.0.0.1 - - [09/Nov/2016 08:32:43] "POST /project_g_to_t HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 2000, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 1991, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 1567, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 1641, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask_cors/extension.py", line 161, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 1544, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 1639, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/paschallj/hgvs_eval/v5/hgvs-eval/venv/lib/python2.7/site-packages/flask/app.py", line 1625, in dispat
```

and

```

self = <json.decoder.JSONDecoder object at 0x7f40a677a810>, s = '<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN"
  "http://www.w3.org/TR/html4/loose.dtd">
<html>
  <he...", line 232, in head
    if self.position >= len(self.data):
TypeError: object of type \'NoneType\' has no len()

-->
', idx = 0

    def raw_decode(self, s, idx=0):
        """Decode a JSON document from ``s`` (a ``str`` or ``unicode``
            beginning with a JSON document) and return a 2-tuple of the Python
            representation and the index in ``s`` where the document ended.

            This can be used to decode a JSON document from a string that may
            have extraneous data at the end.

            """
        try:
            obj, end = self.scan_once(s, idx)
        except StopIteration:
>           raise ValueError("No JSON object could be decoded")
E           ValueError: No JSON object could be decoded

/usr/lib/python2.7/json/decoder.py:382: ValueError


```

the output for me of

```
curl -d hgvs_string="NC_000020.10:g.278701_278703delGGC" -d ac=NM_033089.6  http://0.0.0.0:8000/project_g_to_t
```

is 

```
project_g_to_t(NC_000020.10:g.278701_278703delGGC, NM_033089.6)
127.0.0.1 - - [09/Nov/2016 08:37:56] "POST /project_g_to_t HTTP/1.1" 200 -
{
  "hgvsString": "NM_033089.6:c.471_473delGGC"
}
```

and `http://0.0.0.0:8000/info` works
so I think the server is running, but not sure if these results from 
`hgvs-eval --html report.html --json report.json http://0.0.0.0:8000/` are expected

**Comment by nicoleruiz** [comment]
When I installed the tool in a virtual environment created by conda, I was able to run the example curl command and get the same output as you did. I also got errors when running the hgvs-eval command. I followed your instructions from your first comment on this issue.

I tried installing virtualenv using the preinstalled Python that mac comes with but I was not able to get the tool to work.

**Comment by reece** [comment]
I got those errors too, I think because the endpoints are still just stubs.

Since we've got confirmation that this works as described (modulo the anaconda issue), let's close this issue.

I'm open to considering changes to the current scheme. If any of you would like to do that, let's open a new issue to discuss what we want before we make changes.
