### ISSUE TITLE
can't connect to UTA/biocommons

### ISSUE THREAD

**Issue by jpdna** [biocommons/hgvs-eval#19]
While previously it worked for me, on both Master and nicole_wor1 branches
currently when I run the setup instructions in the README'and run 
python app.y &

I get the below
```
(venv) paschallj@jplap:~/hgvs-eval7/hgvs-eval$ python app.py 
Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from hgvseval.testservice.biocommonsService import BiocommonsService
  File "/home/paschallj/hgvs-eval7/hgvs-eval/hgvseval/testservice/biocommonsService.py", line 10, in <module>
    class BiocommonsService(HGVSTestService):
  File "/home/paschallj/hgvs-eval7/hgvs-eval/hgvseval/testservice/biocommonsService.py", line 12, in BiocommonsService
    hdp = hgvs.dataproviders.uta.connect()
  File "/home/paschallj/hgvs-eval7/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 108, in connect
    conn = UTA_postgresql(url=url, pooling=pooling, application_name=application_name)
  File "/home/paschallj/hgvs-eval7/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 473, in __init__
    super(UTA_postgresql, self).__init__(url)
  File "/home/paschallj/hgvs-eval7/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 183, in __init__
    self._connect()
  File "/home/paschallj/hgvs-eval7/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 488, in _connect
    self._conn = psycopg2.connect(**conn_args)
  File "/home/paschallj/hgvs-eval7/hgvs-eval/venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: invalid port number: "None"
```

Any ideas @reece or @nicoleruiz ?

**Comment by jpdna** [comment]
So here is what I tried exactly:
```
git clone https://github.com/biocommons/hgvs-eval.git
cd hgvs-eval/
make devready
source venv/bin/activate


(venv) paschalj@big1:~/hgvs-eval/v1/hgvs-eval$ python app.py &
[1] 27309
(venv) paschalj@big1:~/hgvs-eval/v1/hgvs-eval$ Traceback (most recent call last):
  File "app.py", line 9, in <module>
    from hgvseval.testservice.biocommonsService import BiocommonsService
  File "/home/paschalj/hgvs-eval/v1/hgvs-eval/hgvseval/testservice/biocommonsService.py", line 10, in <module>
    class BiocommonsService(HGVSTestService):
  File "/home/paschalj/hgvs-eval/v1/hgvs-eval/hgvseval/testservice/biocommonsService.py", line 12, in BiocommonsService
    hdp = hgvs.dataproviders.uta.connect()
  File "/home/paschalj/hgvs-eval/v1/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 108, in connect
    conn = UTA_postgresql(url=url, pooling=pooling, application_name=application_name)
  File "/home/paschalj/hgvs-eval/v1/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 473, in __init__
    super(UTA_postgresql, self).__init__(url)
  File "/home/paschalj/hgvs-eval/v1/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 183, in __init__
    self._connect()
  File "/home/paschalj/hgvs-eval/v1/hgvs-eval/venv/local/lib/python2.7/site-packages/hgvs/dataproviders/uta.py", line 488, in _connect
    self._conn = psycopg2.connect(**conn_args)
  File "/home/paschalj/hgvs-eval/v1/hgvs-eval/venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: invalid port number: "None"

```

**Comment by reece** [comment]
Downgrade psycopg2 to 2.6.2.

psycopg2 2.7 was released a few days ago and is causing hgvs users troubles. I reported the issue here: https://github.com/psycopg/psycopg2/issues/524.

**Comment by dvarrazzo** [comment]
Hi, sorry for the trouble, we are expecting to release a fixed version in a few days.

**Comment by jpdna** [comment]
Thanks @reece 
```
pip uninstall psycopg2
pip install 'psycopg2<2.7'
```
solved the problem
